{"spans": [{"name": "prepare_data_traced", "context": {"span_id": "0xff5021231639e483", "trace_id": "0x32adb4903ac20e82194f97b34a7556ff"}, "parent_id": null, "start_time": 1740522939855848065, "end_time": 1740522939873440764, "status_code": "ERROR", "status_message": "ValueError: y contains previously unseen labels: [np.int64(1)]", "attributes": {"mlflow.traceRequestId": "\"08de1f310de241389b141f458a0bd6a8\"", "mlflow.spanType": "\"UNKNOWN\"", "mlflow.spanFunctionName": "\"prepare_data_traced\"", "mlflow.spanInputs": "{\"train_file\": \"/tmp/pytest-of-root/pytest-0/test_evaluate_model_traced0/train.csv\", \"test_file\": \"/tmp/pytest-of-root/pytest-0/test_evaluate_model_traced0/test.csv\"}"}, "events": [{"name": "exception", "timestamp": 1740522939873407864, "attributes": {"exception.type": "ValueError", "exception.message": "y contains previously unseen labels: [np.int64(1)]", "exception.stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/opentelemetry/trace/__init__.py\", line 589, in use_span\n    yield span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 269, in start_span\n    yield mlflow_span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 145, in _wrapping_logic\n    result = yield  # sync/async function output to be sent here\n             ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 175, in wrapper\n    return wrapping_coro.send(fn(*args, **kwargs))\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/app/main.py\", line 59, in prepare_data_traced\n    X_train, X_test, y_train, y_test = process_data(train_file, test_file)\n                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/data_processing.py\", line 108, in prepare_data\n    y_test = target_encoder.transform(y_test)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/sklearn/preprocessing/_label.py\", line 134, in transform\n    return _encode(y, uniques=self.classes_)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/sklearn/utils/_encode.py\", line 242, in _encode\n    raise ValueError(f\"y contains previously unseen labels: {str(diff)}\")\nValueError: y contains previously unseen labels: [np.int64(1)]\n", "exception.escaped": "False"}}]}], "request": "{\"train_file\": \"/tmp/pytest-of-root/pytest-0/test_evaluate_model_traced0/train.csv\", \"test_file\": \"/tmp/pytest-of-root/pytest-0/test_evaluate_model_traced0/test.csv\"}", "response": null}