{"spans": [{"name": "train_model_traced", "context": {"span_id": "0xc349a2635c9b0ad0", "trace_id": "0x27cdd569ba2c24a6a72cc909e0fb8e8c"}, "parent_id": null, "start_time": 1740523743704782772, "end_time": 1740523745880315678, "status_code": "ERROR", "status_message": "TypeError: test_train_model_traced.<locals>.<lambda>() got an unexpected keyword argument 'registered_model_name'", "attributes": {"mlflow.traceRequestId": "\"9162a3292f9f43be9baa022296e35c12\"", "mlflow.spanType": "\"UNKNOWN\"", "step": "\"model_training\"", "mlflow.spanFunctionName": "\"train_model_traced\"", "mlflow.spanInputs": "{\"X_train\": \"   Total day minutes  ...  Voice mail plan\\n0              120.5  ...                0\\n1              150.3  ...                1\\n\\n[2 rows x 8 columns]\", \"y_train\": \"[0 1]\", \"model_version\": \"test_1.0\"}"}, "events": [{"name": "exception", "timestamp": 1740523745880265678, "attributes": {"exception.type": "TypeError", "exception.message": "test_train_model_traced.<locals>.<lambda>() got an unexpected keyword argument 'registered_model_name'", "exception.stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.12/site-packages/opentelemetry/trace/__init__.py\", line 589, in use_span\n    yield span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 269, in start_span\n    yield mlflow_span\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 145, in _wrapping_logic\n    result = yield  # sync/async function output to be sent here\n             ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/mlflow/tracing/fluent.py\", line 175, in wrapper\n    return wrapping_coro.send(fn(*args, **kwargs))\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/app/main.py\", line 73, in train_model_traced\n    return train_xgb_model(X_train, y_train, model_version=model_version)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/model_training.py\", line 242, in train_model\n    mlflow.xgboost.log_model(\nTypeError: test_train_model_traced.<locals>.<lambda>() got an unexpected keyword argument 'registered_model_name'\n", "exception.escaped": "False"}}]}], "request": "{\"X_train\": \"   Total day minutes  ...  Voice mail plan\\n0              120.5  ...                0\\n1              150.3  ...                1\\n\\n[2 rows x 8 columns]\", \"y_train\": \"[0 1]\", \"model_version\": \"test_1.0\"}", "response": null}